apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: demo-app
spec:
  promotionPolicies:
  - stage: prd
    autoPromotionEnabled: false  # Manual approval required for PRD
---
apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: demo-app
  labels:
    kargo.akuity.io/cred-type: git
type: Opaque
stringData:
  repoURL: https://github.com/breezepatel/demo-gitops-repo
  username: breezepatel  # Your actual GitHub username
  password: ghp_xxxxx  # Your GitHub Personal Access Token with repo write access
