apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prd
  namespace: demo-app
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: demo-app-warehouse
    sources:
      direct: true  # PRD gets freight directly from warehouse

  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/breezepatel/demo-gitops-repo
          checkout:
          - branch: main
            path: ./repo

      - uses: kustomize-set-image
        as: update-image
        config:
          path: ./repo/environments/prd
          images:
          - image: ghcr.io/breezepatel/demo-app-repo/demo-app
            tag: "{{ .Freight.Artifacts[0].Version }}"

      - uses: git-commit
        config:
          path: ./repo
          messageFromSteps:
          - update-image

      - uses: git-push
        config:
          path: ./repo
          targetBranch: main
