apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prd
  namespace: demo-app
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: demo-app-warehouse
    sources:
      direct: true
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://github.com/breezepatel/demo-gitops-repo
      - name: imageRepo
        value: ghcr.io/breezepatel/demo-app-repo/demo-app
      steps:
      - uses: git-clone
        config:
          repoURL: ${{ vars.gitRepo }}
          checkout:
          - branch: main
            path: ./repo
      - uses: kustomize-set-image
        as: update-image
        config:
          path: ./repo/environments/prd
          images:
          - image: ${{ vars.imageRepo }}
            tag: ${{ imageFrom(vars.imageRepo).Tag }}
      - uses: git-commit
        config:
          path: ./repo
          message: "chore(prd): promote ${{ imageFrom(vars.imageRepo).Tag }}"
      - uses: git-push
        config:
          path: ./repo
          targetBranch: main
