apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: demo-app-warehouse
  namespace: demo-app
spec:
  freightCreationPolicy: Automatic
  subscriptions:
  - image:
      repoURL: ghcr.io/breezepatel/demo-app-repo/demo-app
      discoveryLimit: 10
      semverConstraint: ">=1.0.0"
      allowTags: "^[0-9]+\\.[0-9]+\\.[0-9]+$"
