apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo-app
  namespace: demo-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: ghcr.io/breezepatel/demo-app-repo/demo-app:9ed8c93
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: ENVIRONMENT
          value: "dev"
        - name: APP_VERSION
          value: "dev"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
  strategy:
    canary:
      steps:
      - setWeight: 50
      - pause: {duration: 30s}
      - setWeight: 100
